### ISSUE TITLE
Install error: failed to parse the `edition` key

### ISSUE THREAD

**Issue by jfriend00** [alexgorbatchev/crc#73]
If you get an install error that has these in it:

`failed to parse the `edition` key`

or 

 `supported edition values are `2015` or `2018`, but `2021` is unknown`

Then, it's likely because your version of rust is out of date and you need to update it.  I was able to update mine by just typing:

`rustup update`

And, then the installation issue disappeared.  It might be useful if the doc for this module explains this dependency.

**Comment by alexgorbatchev** [comment]
I think you wanted to post this elsewhere, this issues doesn't make sense in the context of this repo.
