### ISSUE TITLE
Doc appears to be written for a module named "crc", not one named "node-crc"

### ISSUE THREAD

**Issue by jfriend00** [alexgorbatchev/crc#74]
For example after installing:

`npm install node-crc`

You cannot follow the doc and use:

`import crc from 'crc';`

As you will get an error message about not being able to find module crc.  Instead, you have to use this:

`import crc from 'node-crc';`

**Comment by alexgorbatchev** [comment]
I renamed the repo to avoid the confusion. You are looking at https://www.npmjs.com/package/node-crc . This repo is for https://www.npmjs.com/package/crc
